### PR TITLE
initial version

### PR DESCRIPTION
**Pull request by jptredoux**

### CODE REVIEW

**Comment by zachsa** [comment]
Ahoy. am I authorized for this?

**Comment by jptredoux** [comment]
@zachsa : invited you to the organisation - check your mail

**Comment by zachsa** [comment]
@jptredoux. I think you still have to assign to me

**Comment by jptredoux** [comment]
@zachsa : you are assigned as a reviewer. couldn't do it before you joined the org ;)

**Review by zachsa — APPROVED** [review]
I'm a proponent for ES 5 syntax since I prefer protype based oop to class based oop. C# actually has a stupid polyfil to allow prototype-like functionality called extension methods just to show how obviously inferior the class abstraction is :p. And until ES 6 generators and iterators are fully supported I don't see a reason to upgrade.

**Review by zachsa — APPROVED** [review]
I'm a proponent for ES 5 syntax since I prefer protype based oop to class based oop. C# actually has a stupid polyfil to allow prototype-like functionality called extension methods just to show how obviously inferior the class abstraction is :p. And until ES 6 generators and iterators are fully supported I don't see a reason to upgrade.

**Review by marten790 — APPROVED** [review]
It all looks good. Nice to see the airbnb linter and yarn being used. Some real clean code you got there

**Pull request merged**
